from io import BytesIO, StringIO
import csv
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from database import get_db
from models.incident import Incident
from models.audit import AuditLog
from auth import get_current_user, require_role
from models.user import User

# PDF
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

router = APIRouter(prefix="/api/reports", tags=["Reports"])


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────
def _parse_date(s: Optional[str]) -> Optional[datetime]:
    if not s:
        return None
    # expects YYYY-MM-DD
    return datetime.strptime(s, "%Y-%m-%d")


def _row_yield(y: float, step: float = 6.5 * mm) -> float:
    return y - step


def _pdf_response(buffer: BytesIO, filename: str) -> StreamingResponse:
    buffer.seek(0)
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return StreamingResponse(buffer, media_type="application/pdf", headers=headers)


def _csv_response(text: str, filename: str) -> StreamingResponse:
    buf = BytesIO(text.encode("utf-8"))
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return StreamingResponse(buf, media_type="text/csv", headers=headers)


def _incident_query(
    db: Session,
    date_from: Optional[str],
    date_to: Optional[str],
    severity: Optional[str],
    status: Optional[str],
    analyst: Optional[str],
    search: Optional[str],
):
    q = db.query(Incident)

    # NOTE: your Incident.timestamp is string ("YYYY-MM-DD HH:MM")
    # lexicographic filter works if format is consistent.
    if date_from:
        q = q.filter(Incident.timestamp >= f"{date_from} 00:00")
    if date_to:
        q = q.filter(Incident.timestamp <= f"{date_to} 23:59")

    if severity and severity != "All":
        q = q.filter(Incident.severity == severity)
    if status and status != "All":
        q = q.filter(Incident.status == status)
    if analyst and analyst != "All":
        q = q.filter(Incident.analyst == analyst)

    if search:
        s = f"%{search}%"
        q = q.filter(Incident.id.ilike(s) | Incident.desc.ilike(s) | Incident.src_ip.ilike(s) | Incident.dst_ip.ilike(s))

    return q.order_by(Incident.timestamp.desc())


def _audit_query(
    db: Session,
    date_from: Optional[str],
    date_to: Optional[str],
    actor: Optional[str],
    change_type: Optional[str],
    search: Optional[str],
):
    q = db.query(AuditLog)

    if date_from:
        q = q.filter(AuditLog.timestamp >= f"{date_from} 00:00")
    if date_to:
        q = q.filter(AuditLog.timestamp <= f"{date_to} 23:59")

    if actor and actor != "All":
        q = q.filter(AuditLog.actor == actor)
    if change_type and change_type != "All":
        q = q.filter(AuditLog.change_type == change_type)

    if search:
        s = f"%{search}%"
        q = q.filter(AuditLog.id.ilike(s) | AuditLog.target.ilike(s) | AuditLog.actor.ilike(s))

    return q.order_by(AuditLog.timestamp.desc())


def _draw_pdf_header(c: canvas.Canvas, title: str, generated_by: str, filters_text: str):
    width, height = A4
    y = height - 20 * mm
    c.setFont("Helvetica-Bold", 14)
    c.drawString(15 * mm, y, title)

    y = _row_yield(y, 7 * mm)
    c.setFont("Helvetica", 9)
    c.drawString(15 * mm, y, f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y = _row_yield(y, 5.5 * mm)
    c.drawString(15 * mm, y, f"Generated by: {generated_by}")
    y = _row_yield(y, 5.5 * mm)
    c.drawString(15 * mm, y, f"Filters: {filters_text}")
    y = _row_yield(y, 4 * mm)
    c.line(15 * mm, y, 195 * mm, y)
    return y - 6 * mm


# ─────────────────────────────────────────────────────────────
# INCIDENTS PDF
# ─────────────────────────────────────────────────────────────
@router.get("/incidents.pdf")
def export_incidents_pdf(
    date_from: Optional[str] = Query(None, alias="from"),
    date_to: Optional[str] = Query(None, alias="to"),
    severity: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    analyst: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "soc_lead", "analyst")),
):
    records = _incident_query(db, date_from, date_to, severity, status, analyst, search).all()

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    filters_text = f"from={date_from or '-'}, to={date_to or '-'}, severity={severity or '-'}, status={status or '-'}, analyst={analyst or '-'}"
    y = _draw_pdf_header(c, "Incidents Report", current_user.username, filters_text)

    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Total records: {len(records)}")
    y = _row_yield(y, 7 * mm)

    c.setFont("Helvetica-Bold", 8)
    c.drawString(15 * mm, y, "ID")
    c.drawString(35 * mm, y, "Time")
    c.drawString(70 * mm, y, "Severity")
    c.drawString(92 * mm, y, "Status")
    c.drawString(118 * mm, y, "Src IP")
    c.drawString(148 * mm, y, "Dst IP")
    c.drawString(178 * mm, y, "Port")
    y = _row_yield(y, 5.5 * mm)
    c.line(15 * mm, y + 2 * mm, 195 * mm, y + 2 * mm)

    c.setFont("Helvetica", 7.5)
    for r in records:
        if y < 20 * mm:
            c.showPage()
            y = height - 20 * mm
            c.setFont("Helvetica-Bold", 8)
            c.drawString(15 * mm, y, "ID")
            c.drawString(35 * mm, y, "Time")
            c.drawString(70 * mm, y, "Severity")
            c.drawString(92 * mm, y, "Status")
            c.drawString(118 * mm, y, "Src IP")
            c.drawString(148 * mm, y, "Dst IP")
            c.drawString(178 * mm, y, "Port")
            y = _row_yield(y, 5.5 * mm)
            c.setFont("Helvetica", 7.5)

        c.drawString(15 * mm, y, str(r.id))
        c.drawString(35 * mm, y, str(r.timestamp)[:16])
        c.drawString(70 * mm, y, str(r.severity))
        c.drawString(92 * mm, y, str(r.status))
        c.drawString(118 * mm, y, str(r.src_ip))
        c.drawString(148 * mm, y, str(r.dst_ip))
        c.drawString(178 * mm, y, str(r.port))
        y = _row_yield(y, 5.2 * mm)

    c.save()
    filename = f"incidents_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return _pdf_response(buffer, filename)


# ─────────────────────────────────────────────────────────────
# AUDITS PDF
# ─────────────────────────────────────────────────────────────
@router.get("/audits.pdf")
def export_audits_pdf(
    date_from: Optional[str] = Query(None, alias="from"),
    date_to: Optional[str] = Query(None, alias="to"),
    actor: Optional[str] = Query(None),
    change_type: Optional[str] = Query(None, alias="changeType"),
    search: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "soc_lead")),
):
    records = _audit_query(db, date_from, date_to, actor, change_type, search).all()

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    filters_text = f"from={date_from or '-'}, to={date_to or '-'}, actor={actor or '-'}, changeType={change_type or '-'}"
    y = _draw_pdf_header(c, "Audit Logs Report", current_user.username, filters_text)

    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Total records: {len(records)}")
    y = _row_yield(y, 7 * mm)

    c.setFont("Helvetica-Bold", 8)
    c.drawString(15 * mm, y, "ID")
    c.drawString(35 * mm, y, "Time")
    c.drawString(70 * mm, y, "Actor")
    c.drawString(95 * mm, y, "Change")
    c.drawString(125 * mm, y, "Target")
    c.drawString(178 * mm, y, "RB")
    y = _row_yield(y, 5.5 * mm)
    c.line(15 * mm, y + 2 * mm, 195 * mm, y + 2 * mm)

    c.setFont("Helvetica", 7.5)
    for r in records:
        if y < 20 * mm:
            c.showPage()
            y = height - 20 * mm
            c.setFont("Helvetica-Bold", 8)
            c.drawString(15 * mm, y, "ID")
            c.drawString(35 * mm, y, "Time")
            c.drawString(70 * mm, y, "Actor")
            c.drawString(95 * mm, y, "Change")
            c.drawString(125 * mm, y, "Target")
            c.drawString(178 * mm, y, "RB")
            y = _row_yield(y, 5.5 * mm)
            c.setFont("Helvetica", 7.5)

        c.drawString(15 * mm, y, str(r.id))
        c.drawString(35 * mm, y, str(r.timestamp)[:16])
        c.drawString(70 * mm, y, str(r.actor))
        c.drawString(95 * mm, y, str(r.change_type))
        c.drawString(125 * mm, y, str(r.target)[:35])  # trim
        c.drawString(178 * mm, y, "Yes" if r.rolled_back else "No")
        y = _row_yield(y, 5.2 * mm)

    c.save()
    filename = f"audit_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return _pdf_response(buffer, filename)


# ─────────────────────────────────────────────────────────────
# INCIDENTS CSV (optional)
# ─────────────────────────────────────────────────────────────
@router.get("/incidents.csv")
def export_incidents_csv(
    date_from: Optional[str] = Query(None, alias="from"),
    date_to: Optional[str] = Query(None, alias="to"),
    severity: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    analyst: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "soc_lead", "analyst")),
):
    rows = _incident_query(db, date_from, date_to, severity, status, analyst, search).all()
    s = StringIO()
    w = csv.writer(s)
    w.writerow(["id", "timestamp", "desc", "type", "severity", "status", "analyst", "src_ip", "dst_ip", "protocol", "port"])
    for r in rows:
        w.writerow([r.id, r.timestamp, r.desc, r.type, r.severity, r.status, r.analyst, r.src_ip, r.dst_ip, r.protocol, r.port])

    filename = f"incidents_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    return _csv_response(s.getvalue(), filename)


# ─────────────────────────────────────────────────────────────
# AUDITS CSV (optional)
# ─────────────────────────────────────────────────────────────
@router.get("/audits.csv")
def export_audits_csv(
    date_from: Optional[str] = Query(None, alias="from"),
    date_to: Optional[str] = Query(None, alias="to"),
    actor: Optional[str] = Query(None),
    change_type: Optional[str] = Query(None, alias="changeType"),
    search: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "soc_lead")),
):
    rows = _audit_query(db, date_from, date_to, actor, change_type, search).all()
    s = StringIO()
    w = csv.writer(s)
    w.writerow(["id", "timestamp", "actor", "change_type", "target", "action", "details", "rolled_back"])
    for r in rows:
        w.writerow([r.id, r.timestamp, r.actor, r.change_type, r.target, r.action, r.details, r.rolled_back])

    filename = f"audit_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    return _csv_response(s.getvalue(), filename)