"""init_configuration

Revision ID: 02bbdfaf6c34
Revises: 
Create Date: 2026-03-05 06:06:54.925747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02bbdfaf6c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('min_severity', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=True),
    sa.Column('baseline_window', sa.Integer(), nullable=True),
    sa.Column('packet_size_mult', sa.Float(), nullable=True),
    sa.Column('conn_rate_mult', sa.Float(), nullable=True),
    sa.Column('dns_query_rate', sa.Integer(), nullable=True),
    sa.Column('traffic_volume_mult', sa.Float(), nullable=True),
    sa.Column('alert_cooldown', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_ips',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.String(length=100), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('network_interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ransom_rules',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevelenum'), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sig_rules',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severityenum'), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('alert', 'drop', 'block', 'log', name='actionenum'), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_retention_days', sa.Integer(), nullable=True),
    sa.Column('max_packet_capture', sa.Integer(), nullable=True),
    sa.Column('performance_mode', sa.String(length=20), nullable=True),
    sa.Column('auto_block_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_block_threshold', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('sig_rules')
    op.drop_table('ransom_rules')
    op.drop_table('network_interfaces')
    op.drop_table('blocked_ips')
    op.drop_table('anomaly_config')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
