"""add_incidents

Revision ID: 11c56b5162ba
Revises: 02bbdfaf6c34
Create Date: 2026-03-09 04:15:58.609852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c56b5162ba'
down_revision: Union[str, Sequence[str], None] = '02bbdfaf6c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_ip_actions',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actioned_by', sa.String(length=100), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('det_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_incident_id'), 'incident_timeline', ['incident_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_index(op.f('ix_incident_timeline_incident_id'), table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_table('detections')
    op.drop_table('detection_ip_actions')
    # ### end Alembic commands ###
