"""add_audits

Revision ID: 56b55f0399bf
Revises: 7bb1cc1172ef
Create Date: 2026-03-19 07:20:12.752488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b55f0399bf'
down_revision: Union[str, Sequence[str], None] = '7bb1cc1172ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('malicious_ips',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('avg_sev', sa.String(length=20), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('last_seen', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('malicious_ips')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
