"""add_phone_verification_to_users

Revision ID: 693b104ec423
Revises: 786723d2a8a6
Create Date: 2026-05-28 20:20:30.976903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '693b104ec423'
down_revision: Union[str, Sequence[str], None] = '786723d2a8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocked_ips', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('blocked_ips', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('blocked_ips', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_blocked_ips_id'), 'blocked_ips', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_ips_ip'), 'blocked_ips', ['ip'], unique=True)
    op.drop_column('blocked_ips', 'blocked_at')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'phone')
    op.add_column('blocked_ips', sa.Column('blocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_blocked_ips_ip'), table_name='blocked_ips')
    op.drop_index(op.f('ix_blocked_ips_id'), table_name='blocked_ips')
    op.alter_column('blocked_ips', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('blocked_ips', 'created_at')
    op.drop_column('blocked_ips', 'id')
    # ### end Alembic commands ###
