"""add_captured_packets

Revision ID: 786723d2a8a6
Revises: 2137796c30e2
Create Date: 2026-04-05 18:52:54.405787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786723d2a8a6'
down_revision: Union[str, Sequence[str], None] = '2137796c30e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captured_packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captured_packets_created_at'), 'captured_packets', ['created_at'], unique=False)
    op.create_index(op.f('ix_captured_packets_dst_ip'), 'captured_packets', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_captured_packets_protocol'), 'captured_packets', ['protocol'], unique=False)
    op.create_index(op.f('ix_captured_packets_src_ip'), 'captured_packets', ['src_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captured_packets_src_ip'), table_name='captured_packets')
    op.drop_index(op.f('ix_captured_packets_protocol'), table_name='captured_packets')
    op.drop_index(op.f('ix_captured_packets_dst_ip'), table_name='captured_packets')
    op.drop_index(op.f('ix_captured_packets_created_at'), table_name='captured_packets')
    op.drop_table('captured_packets')
    # ### end Alembic commands ###
